# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 249578674cae6fe5412e1952f8941dc5bc8f9a6a1aea850efffa77797b39a8538034c7d39b5871dda2d2286502646bffca810b902e8143dc08d02d182ffed096

test:
  secret_key_base: 0c0479443484bbdd92d3e5f0da0cb067746be542bde8e4536195ab07e1d0e37ed9df6d943f8f82906e99f988a61a3c7994164fec06f31441dcb6fcd859c0fbc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
